--CREATE DATABASE Assignment_PRJ1;
--USE Assignment_PRJ1;

CREATE TABLE USER_ROLE (
    ROLE_ID INT NOT NULL PRIMARY KEY,
    ROLE_NAME NVARCHAR(200)
);

CREATE TABLE USERS (
    USER_NAME VARCHAR(200) NOT NULL PRIMARY KEY,
    FULLNAME VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    ROLE_ID INT NOT NULL,
    CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES USER_ROLE(ROLE_ID) ON DELETE CASCADE
);
ALTER TABLE USERS 
ADD STATUS VARCHAR(50) DEFAULT 'ACTIVE' NOT NULL;
ALTER TABLE USERS 
ADD TOKEN VARCHAR(500) NULL;
CREATE TABLE STYLE_PRODUCT (
    STYLE_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    STYLE_NAME VARCHAR(200) NOT NULL
);

CREATE TABLE PRODUCT_LINE (
    LINE_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    LINE_NAME VARCHAR(200) NOT NULL
);

CREATE TABLE MATERIAL (
    MAT_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    MAT_NAME VARCHAR(200) NOT NULL
);

CREATE TABLE PRODUCT_COLOR (
    COLOR_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    COLOR_NAME VARCHAR(200) NOT NULL,
    COLOR_CODE VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCT_SIZE (
    SIZE_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    SIZE_NUM DECIMAL(5, 2) NOT NULL UNIQUE
);

CREATE TABLE PRODUCT_SALE (
    SALE_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    SALE_NUM DECIMAL(5, 2) NOT NULL UNIQUE
);

CREATE TABLE SHOES_PRODUCT (
    SHOES_ID VARCHAR(200) NOT NULL PRIMARY KEY,
    SHOES_NAME VARCHAR(200) NOT NULL,
    PRODUCE_DATE DATE NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    QUANTITY INT NOT NULL,
    GENDER VARCHAR(10) NOT NULL CHECK (GENDER IN ('Male', 'Female', 'Unisex')),
    DESCRIPTION VARCHAR(200),
    STATUS VARCHAR(10) NOT NULL CHECK (STATUS IN ('Soldout', 'Sale', 'Available')),
    STYLE_ID VARCHAR(10) NOT NULL,
    LINE_ID VARCHAR(10) NOT NULL,
    MAT_ID VARCHAR(10) NOT NULL,
    SALE_ID VARCHAR(20) NOT NULL,
    CONSTRAINT FK_STYLE_ID FOREIGN KEY (STYLE_ID) REFERENCES STYLE_PRODUCT(STYLE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LINE_ID FOREIGN KEY (LINE_ID) REFERENCES PRODUCT_LINE(LINE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MAT_ID FOREIGN KEY (MAT_ID) REFERENCES MATERIAL(MAT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SALE_ID FOREIGN KEY (SALE_ID) REFERENCES PRODUCT_SALE(SALE_ID) ON DELETE CASCADE
);

CREATE TABLE SHOES_COLOR_SIZE (
    SHOES_ID VARCHAR(200) NOT NULL,
    COLOR_ID VARCHAR(10) NOT NULL,
    SIZE_ID VARCHAR(20) NOT NULL,
    STOCK INT NOT NULL,
    PRIMARY KEY (SHOES_ID, COLOR_ID, SIZE_ID),
    CONSTRAINT FK_SHOES_ID FOREIGN KEY (SHOES_ID) REFERENCES SHOES_PRODUCT(SHOES_ID) ON DELETE CASCADE,
    CONSTRAINT FK_COLOR_ID FOREIGN KEY (COLOR_ID) REFERENCES PRODUCT_COLOR(COLOR_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SIZE_ID FOREIGN KEY (SIZE_ID) REFERENCES PRODUCT_SIZE(SIZE_ID) ON DELETE CASCADE
);

CREATE TABLE CART (
    CART_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    USER_NAME VARCHAR(200) NOT NULL, 
    CONSTRAINT FK_CART_USER FOREIGN KEY (USER_NAME) REFERENCES USERS(USER_NAME) ON DELETE CASCADE
);

CREATE TABLE CART_DETAIL (
    CART_ID VARCHAR(20) NOT NULL,
    SHOES_ID VARCHAR(200) NOT NULL,
    COLOR_ID VARCHAR(10) NOT NULL,
    SIZE_ID VARCHAR(20) NOT NULL,
    QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
    PRICE DECIMAL(10,2) NOT NULL, 
    PRIMARY KEY (CART_ID, SHOES_ID, COLOR_ID, SIZE_ID),  
    CONSTRAINT FK_CART_DETAIL_CART FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CART_DETAIL_SHOES FOREIGN KEY (SHOES_ID, COLOR_ID, SIZE_ID) 
        REFERENCES SHOES_COLOR_SIZE(SHOES_ID, COLOR_ID, SIZE_ID) ON DELETE CASCADE
);


CREATE TABLE ORDERS (
    ORDER_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    FULLNAME VARCHAR(200) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    DATE_ORDERED DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled')), 
    ADDRESS VARCHAR(200) NOT NULL,
	METHOD_PAY VARCHAR(50) NOT NULL CHECK (METHOD_PAY IN ('Online', 'Offline')),
	SUBTOTAL DECIMAL(10,2)not null,
	DISCOUNT DECIMAL(10,2)not null,
    TOTAL_PRICE DECIMAL(10,2) NOT NULL,
	USER_NAME VARCHAR(200) NOT NULL, 
    CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_NAME) REFERENCES USERS(USER_NAME) ON DELETE CASCADE
);


CREATE TABLE ORDERS_DETAIL (
    ORDER_ID VARCHAR(20) NOT NULL,
    SHOES_ID VARCHAR(200) NOT NULL,
    COLOR_ID VARCHAR(10) NOT NULL,
    SIZE_ID VARCHAR(20) NOT NULL,
    QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
    PRICE DECIMAL(10,2) NOT NULL, 
    PRIMARY KEY (ORDER_ID, SHOES_ID, COLOR_ID, SIZE_ID),
    CONSTRAINT FK_ORDER_DETAIL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_DETAIL_SHOES FOREIGN KEY (SHOES_ID, COLOR_ID, SIZE_ID) 
        REFERENCES SHOES_COLOR_SIZE(SHOES_ID, COLOR_ID, SIZE_ID) ON DELETE CASCADE
);

CREATE TABLE FAVOURITE (
    FAV_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    USER_NAME VARCHAR(200) NOT NULL, 
    CONSTRAINT FK_FAV_USER FOREIGN KEY (USER_NAME) REFERENCES USERS(USER_NAME) ON DELETE CASCADE
);

CREATE TABLE FAVOURITE_DETAIL (
    FAV_ID VARCHAR(20) NOT NULL,
    SHOES_ID VARCHAR(200) NOT NULL,
    PRIMARY KEY (FAV_ID, SHOES_ID),
    CONSTRAINT FK_FAV_DETAIL_FAV FOREIGN KEY (FAV_ID) REFERENCES FAVOURITE(FAV_ID) ON DELETE CASCADE,
    CONSTRAINT FK_FAV_DETAIL_SHOES FOREIGN KEY (SHOES_ID) REFERENCES SHOES_PRODUCT(SHOES_ID) ON DELETE CASCADE
);

CREATE TABLE VOUCHER (
    ID VARCHAR(36) PRIMARY KEY, 
    CODE VARCHAR(50) UNIQUE NOT NULL, 
    DISCOUNT DECIMAL(10,2) NOT NULL, 
    QUANTITY INT NOT NULL DEFAULT 1, 
    START_DATE DATETIME NOT NULL, 
    END_DATE DATETIME NOT NULL, 
    STATUS VARCHAR(10) NOT NULL CHECK (STATUS IN ('ACTIVE', 'EXPIRED'))		DEFAULT 'ACTIVE' 
);